# Etapa 1: Build da aplicação
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

# Etapa 2: Executar a aplicação
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/veiculos-api-1.0-SNAPSHOT.jar app.jar
CMD ["java", "-jar", "app.jar"]
